title: Rachel Flanders
email: rachelnflanders@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Technical writing portfolio and resume.
theme: minima

# social links
github_username:  rachelnf # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
